version: "3.2"

services:
  demoproj:
    image: wanjia1/prometheus-demo:1.0
    restart: always
    container_name: demoproj
    ports:
      - "9001:9001"
    expose:
      - "9001"
    networks:
      - prometheus-demo
  prometheus:
    image: prom/prometheus
    restart: always
    #network_mode: "host"
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - /Users/wangjian/software/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - demoproj
    networks:
      - prometheus-demo
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - prometheus
      - demoproj
    networks:
      - prometheus-demo
networks:
  prometheus-demo:
